### ISSUE TITLE
如何使用你的库实现请求队列

### ISSUE THREAD

**Issue by gdfyj90** [YouXianMing/GCD-Program#5]
请求A返回数据a，请求B返回数据b，现在需要得到a+b的值请问用哪个方法

**Comment by YouXianMing** [comment]
这个可以通过信号量semaphore来操作呢，可能有点复杂，你可以参考这个写demo试试：

// init semaphore
    GCDSemaphore *semaphore = [GCDSemaphore new];

```
// wait
[GCDQueue executeInGlobalQueue:^{
    [semaphore wait];

    // todo sth else
}];


// signal
[GCDQueue executeInGlobalQueue:^{
    // do sth

    [semaphore signal];
}];
```

考虑到复用性，还是建议你使用NSOperationQueue
